version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./storage:/var/www/storage
            - ./bootstrap/cache:/var/www/bootstrap/cache
        depends_on:
            - db
        networks:
            - laravel

    webserver:
        image: nginx:latest
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: pos-project
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
        networks:
            - laravel

    node:
        image: node:20
        container_name: node_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
        ports:
            - "5173:5173"
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
volumes:
    dbdata:
